import { HomeExperience } from "@/components/HomeExperience";
import type { TimelineItem } from "@/lib/content";

const events: TimelineItem[] = [
  { id:"xiongnu", yearLabel:"МЭӨ 209", eraMn:"Хүннү гүрэн", eraEn:"Xiongnu Empire", titleMn:"Модун шаньюйн хүчирхэгжилт", titleEn:"The rise of Modu Chanyu", summaryMn:"Хүннү гүрэн Төв Азийн хамгийн хүчирхэг нүүдэлчдийн холбооны нэг болж, төр ба цэргийн зохион байгуулалтаараа ялгарсан.", summaryEn:"The Xiongnu became one of Central Asia's most powerful nomadic confederations, distinguished by state and military organization.", factsMn:["Төв Азийн өргөн нутагт нөлөөгөө тогтоов","Нүүдэлчдийн төрийн эртний загварыг хөгжүүлэв"], factsEn:["Expanded influence across Central Asia","Developed an early model of nomadic statehood"], sortOrder:10, published:true },
  { id:"1206", yearLabel:"1206", eraMn:"Чингис хааны үе", eraEn:"Age of Chinggis Khaan", titleMn:"Их Монгол Улс байгуулагдав", titleEn:"The Great Mongol State was founded", summaryMn:"Тэмүжин Их хуралдайгаар Чингис хаанд өргөмжлөгдөж, Монголын овог аймгуудыг нэгтгэн шинэ төр, хууль, цэргийн тогтолцоог бүрдүүлэв.", summaryEn:"Temujin was proclaimed Chinggis Khaan, unifying the Mongol tribes under a new political, legal and military system.", factsMn:["Арвантын зохион байгуулалт бэхжив","Евразийн түүхийн шинэ үе эхлэв"], factsEn:["The decimal organization was strengthened","A new era in Eurasian history began"], sortOrder:20, published:true },
  { id:"1235", yearLabel:"1235", eraMn:"Өгэдэй хааны үе", eraEn:"Age of Ögedei Khaan", titleMn:"Хархорум нийслэл болов", titleEn:"Karakorum became the imperial capital", summaryMn:"Хархорум төр, худалдаа, гар урлал, олон шашны уулзвар болсон дэлхийн хот болон хөгжсөн.", summaryEn:"Karakorum developed into a cosmopolitan center of government, trade, craftsmanship and religious diversity.", factsMn:["Олон улсын худалдаачид цуглардаг байв","Өртөөний сүлжээ улам хөгжөв"], factsEn:["Hosted international merchants","The imperial relay network expanded"], sortOrder:30, published:true },
  { id:"1911", yearLabel:"1911", eraMn:"Тусгаар тогтнолын сэргэлт", eraEn:"Revival of independence", titleMn:"Үндэсний эрх чөлөөний хувьсгал", titleEn:"The National Revolution", summaryMn:"Монголчууд Манж Чин улсын эрхшээлээс гарч, Богд хаант Монгол Улсыг тунхаглав.", summaryEn:"Mongolia declared independence from Qing rule and established the Bogd Khanate.", factsMn:["Тусгаар тогтнолын шинэ үе эхлэв","Богд хаант төр байгуулагдав"], factsEn:["A new era of independence began","The Bogd Khanate was established"], sortOrder:40, published:true },
  { id:"1990", yearLabel:"1990", eraMn:"Орчин үеийн Монгол", eraEn:"Modern Mongolia", titleMn:"Ардчилсан хувьсгал", titleEn:"The Democratic Revolution", summaryMn:"Тайван жагсаал, хэлэлцээ, улс төрийн шинэчлэлийн үр дүнд Монгол Улс олон намын ардчилсан тогтолцоонд шилжив.", summaryEn:"Peaceful demonstrations, dialogue and political reform led Mongolia toward a multi-party democratic system.", factsMn:["Олон намын тогтолцоо бүрдэв","1992 онд шинэ Үндсэн хууль батлагдав"], factsEn:["A multi-party system emerged","A new constitution was adopted in 1992"], sortOrder:50, published:true }
];

export default function HomePage() {
  return <HomeExperience events={events} />;
}
